//** Polyglot Commands ***//
const LIST_SERVICES_REQUEST = "LIST_SERVICES_REQUEST";
const LIST_SERVICES_RESPONSE = "LIST_SERVICES_RESPONSE";

const CALL_SERVICE_REQUEST = "CALL_SERVICE_REQUEST";
const CALL_SERVICE_RESPONSE = "CALL_SERVICE_RESPONSE";
//************************//

//** Dragoman Commands ***//
const VALIDATE_PATHS_REQUEST = "VALIDATE_PATHS_REQUEST";
const VALIDATE_PATHS_RESPONSE = "VALIDATE_PATHS_RESPONSE";

const POST_LOGS = "POST_LOGS";
const LOG_LEVELS = {
    WARN: 'WARN',
    INFO: 'INFO',
    DEBUG: 'DEBUG',
}
// TODO: Define different levels as constants

const CANCEL_REQUEST = "CANCEL_REQUEST";
const CANCEL_REQUEST_RESPONSE = "CANCEL_REQUEST_RESPONSE";
//************************//

module.exports = {
    LIST_SERVICES_REQUEST,
    LIST_SERVICES_RESPONSE,
    CALL_SERVICE_REQUEST,
    CALL_SERVICE_RESPONSE,
    VALIDATE_PATHS_REQUEST,
    VALIDATE_PATHS_RESPONSE,
    POST_LOGS,
    LOG_LEVELS,
    CANCEL_REQUEST,
    CANCEL_REQUEST_RESPONSE
}