const LIST_SERVICES_REQUEST = "LIST_SERVICES_REQUEST";
const LIST_SERVICES_RESPONSE = "LIST_SERVICES_RESPONSE";
const CALL_SERVICE_REQUEST = "CALL_SERVICE_REQUEST";
const CALL_SERVICE_RESPONSE = "CALL_SERVICE_RESPONSE";

module.exports = {
    LIST_SERVICES_REQUEST,
    LIST_SERVICES_RESPONSE,
    CALL_SERVICE_REQUEST,
    CALL_SERVICE_RESPONSE
}