export const LIST_SERVICES_REQUEST = "LIST_SERVICES_REQUEST";
export const LIST_SERVICES_RESPONSE = "LIST_SERVICES_RESPONSE";
export const CALL_SERVICE_REQUEST = "CALL_SERVICE_REQUEST";
export const CALL_SERVICE_RESPONSE = "CALL_SERVICE_RESPONSE";
