//** Polyglot Commands ***//
const LIST_SERVICES_REQUEST = "LIST_SERVICES_REQUEST";
const LIST_SERVICES_RESPONSE = "LIST_SERVICES_RESPONSE";

const CALL_SERVICE_REQUEST = "CALL_SERVICE_REQUEST";
const CALL_SERVICE_RESPONSE = "CALL_SERVICE_RESPONSE";
//************************//

//** Polyglot Commands ***//
const VALIDATE_PATH_REQUEST = "VALIDATE_PATH_REQUEST";
const VALIDATE_PATH_RESPONSE = "VALIDATE_PATH_RESPONSE";

const POST_LOGS = "POST_LOGS"
//************************//

module.exports = {
    LIST_SERVICES_REQUEST,
    LIST_SERVICES_RESPONSE,
    CALL_SERVICE_REQUEST,
    CALL_SERVICE_RESPONSE,
    VALIDATE_PATH_REQUEST,
    VALIDATE_PATH_RESPONSE,
    POST_LOGS
}